language: node_js
node_js:
  - 12
  - 10
script:
  - sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic

  - cd zazic-scale-up
  - npm ci
  - npx medic-conf --no-check convert-app-forms convert-contact-forms compile-app-settings
  - npm run eslint
  - npm run test-unit

  - cd ../itech-aurum
  - npm ci
  - npx medic-conf --no-check convert-app-forms convert-contact-forms compile-app-settings
  - npm run eslint
  - npm run unittest