language: node_js
node_js:
    - 10
env:
    - PROJECT=zazic-scale-up
before_install:
    - sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
    - cd $PROJECT
script: npm run travis
