name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 16.x]
        application: ['./itech-aurum', './itech-malawi', './itech-rsa', './zazic', './zazic-scale-up']

    defaults:
      run:
        working-directory: ${{ matrix.application }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo python -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
    - run: npm ci
    - run: npm test
